// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  let SUPABASE_URL = "";
  let SUPABASE_PUBLISHABLE_KEY = "";

  try {
    if (typeof import.meta !== "undefined" && import.meta.env) {
      SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
      SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
    }
  } catch (e) {
    // Ignore error in environments where import.meta is not allowed
  }

  // Fallback to process.env
  SUPABASE_URL =
    SUPABASE_URL || (typeof process !== "undefined" ? (process.env?.SUPABASE_URL ?? "") : "");
  SUPABASE_PUBLISHABLE_KEY =
    SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== "undefined" ? (process.env?.SUPABASE_PUBLISHABLE_KEY ?? "") : "");

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please check your .env file.`;

    // During SSR OR if environment variables are missing on the client,
    // we don't want to crash the whole app immediately.
    // We log the error and return a dummy client.
    console.error(`[Supabase] ${message}`);

    const dummyClient = {
      auth: {
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
        getSession: async () => ({ data: { session: null }, error: null }),
        getUser: async () => ({ data: { user: null }, error: null }),
        signOut: async () => ({ error: null }),
      },
      from: () => ({
        select: () => ({
          eq: () => ({
            single: async () => ({ data: null, error: { message: "Supabase not configured" } }),
            order: () => ({ data: [], error: null }),
          }),
          order: () => ({ data: [], error: null }),
        }),
      }),
    };

    return dummyClient as unknown as SupabaseClient<Database>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      flowType: "pkce",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
